version: "3.9"
services:
  database:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    # env_file:
      # - .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mongo-data:/data/db
      #- ./db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh

  express:
    build: backend
    container_name: express   
    restart: always
    ports:
      - "3000:3000"
    environment:
      - EXPRESS_SKIP_DB_WAIT=0
      - EXPRESS_SKIP_DB_MIGRATION=0
      - EXPRESS_SKIP_NPM_INSTALL=0
      - EXPRESS_SKIP_BOWER_INSTALL=0
    links:
      - database 

volumes:
  mongo-data:
