version: "3.9"
services:
  database:
    image: mongo
    container_name: mean_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mongo-data:/data/db

  express:
    build: backend
    container_name: mean_express   
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - EXPRESS_SKIP_DB_WAIT=0
      - EXPRESS_SKIP_DB_MIGRATION=0
      - EXPRESS_SKIP_NPM_INSTALL=0
      - EXPRESS_SKIP_BOWER_INSTALL=0
    links:
      - database 

volumes:
  mongo-data:
